name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: user
      GO_VERSION: 1.22

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download && go install github.com/mattn/goveralls@latest

      - name: Install/Downgrade MongoDB to version 3.6
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"

      - name: Unit Tests
        run: go test -v ./...

      - name: Create cover profile
        run: make coverprofile

      - name: Run Docker Test
        run: make dockertest

      - name: Submit Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=cover.profile -service=github

      # Push to dockerhub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push user to Docker Hub
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          context: .
          file: docker/user/Dockerfile-release
          push: true
          tags: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }},${{ env.GROUP }}/${{ env.REPO }}:latest

      - name: Push user-db to Docker Hub
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          context: docker/user-db
          file: docker/user-db/Dockerfile
          push: true
          tags: ${{ env.GROUP }}/${{ env.REPO }}-db:${{ github.sha }},${{ env.GROUP }}/${{ env.REPO }}-db:latest
